name: CI
on: [ push, pull_request ]

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check go mod
        run: |
          export PATH=${GOROOT}/bin:$PATH
          go version
          go mod tidy
          git diff --exit-code go.mod

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run CI
        # https://github.com/actions/setup-go/issues/107#issuecomment-854071850
        run: |
          cp -f `which go` /usr/bin/go
          # export PATH=${GOROOT}/bin:$PATH
          go version
          make ci
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
